OP-11496 : Added Maping URL for pagination APIs in dashboard, platform and SAPOR
OpsMx/gate pull request #120
Opened 2022-01-27 17:19 UTC by sriharshakancharla

https://devopsmx.atlassian.net/browse/OP-11496

We prefer small, well tested pull requests.

Please refer to [Contributing to Spinnaker](https://spinnaker.io/community/contributing/).

When filling out a pull request, please consider the following:

* Follow the commit message conventions [found here](https://spinnaker.io/community/contributing/submitting/).
* Provide a descriptive summary for your changes.
* If it fixes a bug or resolves a feature request, be sure to link to that issue.
* Add inline code comments to changes that might not be obvious.
* Squash your commits as you keep adding changes.
* Add a comment to @spinnaker/reviewers for review if your issue has been outstanding for more than 3 days.

Note that we are unlikely to accept pull requests that add features without prior discussion. The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.

2022-01-27 17:29 UTC, gopaljayanthi commented
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://spin.prod.opsmx.com/#/applications/gcp-gitprtrigger/executions/details/01FTE8SNFF6K0CFN768DRQ1N4K

2022-01-28 07:31 UTC, gopaljayanthi commented
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://spin.prod.opsmx.com/#/applications/gcp-gitprtrigger/executions/details/01FTFSGQBJ4MX30JNZWY8PXBKB

2022-01-28 08:32 UTC, Pranav-b-7 requested changes

2022-01-28 08:32 UTC, Pranav-b-7 commented on gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OpsmxDashboardService.groovy
> +                               @Query("pageLimit") String pageLimit,
pageNo and pageLimit has to be Integer rit. ?

2022-01-28 08:43 UTC, gopaljayanthi commented
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://spin.prod.opsmx.com/#/applications/gcp-gitprtrigger/executions/details/01FTFXM2T2PQ2CZRNPEN66Z4WM

2022-01-28 08:43 UTC, sriharshakancharla commented on gate-web/src/main/groovy/com/netflix/spinnaker/gate/services/internal/OpsmxDashboardService.groovy
> +                               @Query("pageLimit") String pageLimit,
Yes. Changed to Integer

2022-01-28 09:48 UTC, Pranav-b-7 approved these changes

2022-01-28 09:48 UTC, merged