OP-14834: invalidate session and throw SAMLAuthenticationException to redirect to auth entry point.
OpsMx/gate pull request #210
Opened 2022-05-17 10:33 UTC by rahul-chekuri

https://devopsmx.atlassian.net/browse/OP-14834

2022-05-17 10:33 UTC, opsmxuser commented
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01G38S8444QSKSMNFTQ8D0659Z

2022-05-17 10:41 UTC, opsmxuser commented
This PR  triggered this build in this execution, please merge to master only if this succeeds:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01G38S8C9VBGDDZVCXWKXSKT16

2022-05-17 10:50 UTC, opsmxuser commented
SUCCESSFUL RunTests RESULT: <b>Tests run: 201, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 186.348 sec</b> Reviewers ,  this PR did not cause the failures in  https://jenkins.opsmx.net:8181/jenkins/job/Dev-run-tests-on-gitpr-parallel/ws/emailable-report-125.html

2022-05-18 05:53 UTC, Pranav-b-7 requested changes

2022-05-18 05:53 UTC, Pranav-b-7 commented on gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
> +    SamlAuthTokenUpdateFilter authTokenUpdateFilter = new SamlAuthTokenUpdateFilter()
Use autowiring instead of the new operator for instantiating .

2022-05-18 05:53 UTC, Pranav-b-7 commented on gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
> +        BasicAuthenticationFilter.class)
Why is it registered after BasicAuthentication ? If there is some exception thrown in BasicAuthentication will your customized filter get executed ?

2022-05-18 05:57 UTC, rahul-chekuri commented on gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
> +    SamlAuthTokenUpdateFilter authTokenUpdateFilter = new SamlAuthTokenUpdateFilter()
this is a one-time operation. and this how similar things configured in other places.

2022-05-18 06:00 UTC, rahul-chekuri commented on gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
> +        BasicAuthenticationFilter.class)
All SAML filters should come after this. We can witness the same if we check saml configurer. If there is auth exception happens in the basic filter then it don't need to execute my custom filter.

2022-05-18 06:07 UTC, Pranav-b-7 commented on gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
> +    SamlAuthTokenUpdateFilter authTokenUpdateFilter = new SamlAuthTokenUpdateFilter()
Doest matter one time or 2 time operation. if you use new operator, then spring will not consider that class as a bean and also will not add that dependency into IOC container. Its good to have all the beans injected in IOC container

2022-05-18 06:11 UTC, rahul-chekuri commented on gate-saml/src/main/groovy/com/netflix/spinnaker/gate/security/saml/SamlSsoConfig.groovy
> +    SamlAuthTokenUpdateFilter authTokenUpdateFilter = new SamlAuthTokenUpdateFilter()
We don't need this bean in the container as we don't have to inject it anywhere else in the system. Also we don't need this one for other auth types like LDAP, basic, etc that is the reason they are not auto wiring this beans in the other places

2022-06-07 14:10 UTC, Pranav-b-7 approved these changes

2022-06-07 14:10 UTC, merged