OP-17106: Added SamlSsoEventPublishConfig to update ApplicationEventPublisher
OpsMx/gate pull request #234
Opened 2022-08-11 11:57 UTC by rahul-chekuri

https://devopsmx.atlassian.net/browse/OP-17106

2022-08-11 11:57 UTC, opsmxuser commented
This PR  triggered this build in this execution, please wait for it  and child pipelines to succeed before merging:  https://isd.prod.opsmx.net/deck/#/applications/gcp-gitprtrigger/executions/details/01GA6C8BYJ7C7NNRPXQB1D0F48

2022-08-11 11:57 UTC, opsmxuser commented
This PR  triggered this build in this execution, please merge to v4.0 branch only if this succeeds:  https://isd.prod.opsmx.net/deck/#/applications/isd40/executions/details/01GA6C8Y2Y5XWHXA2HDRBFK7Q8

2022-08-11 12:11 UTC, opsmxuser commented
RunTestJar RESULT: <b>Tests run: 229, Failures: 14, Errors: 0, Skipped: 29, Time elapsed: 417.686 sec <<< FAILURE!</b> Reviewers , please check that the changes in this PR did not cause the failures in  http://jenkins.opsmx.net:8181/jenkins/job/Dev-API-Automation-Test-v4.0/ws/emailable-report-214.html

2022-08-11 13:16 UTC, Pranav-b-7 requested changes

2022-08-11 13:16 UTC, Pranav-b-7 commented on gate-web/src/main/java/com/opsmx/spinnaker/gate/audit/AuthenticationAuditListener.java
> +    AuditData data = new AuditData(name);
Only the name field is passed ? why is it so minimal.. I think it would be better to pass the roles and usernames

2022-08-11 13:20 UTC, rahul-chekuri commented on gate-web/src/main/java/com/opsmx/spinnaker/gate/audit/AuthenticationAuditListener.java
> +    AuditData data = new AuditData(name);
the name we are passing here is the user name. We are not using anything else other than the name. There is enough to add more fields on a need basis.

2022-08-12 05:35 UTC, ramyaravi-opsmx approved these changes

2022-08-12 05:35 UTC, merged