OP-18616: added api to valid ldap Connection/Authentication.
OpsMx/gate pull request #314
Opened 2023-01-05 13:53 UTC by rahul-chekuri

2023-01-05 13:55 UTC, rahul-chekuri commented on docker_build/gate.yml
> +  ldapConfigProps:
These are some properties with defaults that will be common for any LDAP.

2023-01-05 13:55 UTC, rahul-chekuri commented on docker_build/gate.yml
> +  ldapConfigProps:
Without these we cant create LDAP in keycloak

2023-01-05 13:56 UTC, rahul-chekuri commented on gate-web/src/main/java/com/opsmx/spinnaker/gate/controller/AuthConfigurerController.java
> +  public ResponseEntity<String> validateLdapAuthConnection(
New API to testLDAPConnection.

2023-01-06 05:42 UTC, Pranav-b-7 requested changes

2023-01-06 05:42 UTC, Pranav-b-7 commented on gate-web/src/main/java/com/opsmx/spinnaker/gate/model/KeycloakProperties.java
> +@ConfigurationProperties(prefix = "keycloak.ldapconfigprops")
Add feature flag condition here and make sure the autowiring does not fail when the flag is disabled

2023-01-06 05:42 UTC, Pranav-b-7 commented on gate-web/src/main/java/com/opsmx/spinnaker/gate/controller/AuthConfigurerController.java
> +    String status = keycloakAuthUtils.validate(testLdapConnectionRepresentation);
Why the util class is called directly from controller ? it has to be from the service layer rit ?

2023-01-06 05:45 UTC, rahul-chekuri commented on gate-web/src/main/java/com/opsmx/spinnaker/gate/controller/AuthConfigurerController.java
> +    String status = keycloakAuthUtils.validate(testLdapConnectionRepresentation);
this is only for LDAP not for all so calling directly

2023-01-06 05:45 UTC, rahul-chekuri commented on gate-web/src/main/java/com/opsmx/spinnaker/gate/controller/AuthConfigurerController.java
> +    String status = keycloakAuthUtils.validate(testLdapConnectionRepresentation);
service layer is generic one for all types

2023-01-06 05:51 UTC, rahul-chekuri commented on gate-web/src/main/java/com/opsmx/spinnaker/gate/model/KeycloakProperties.java
> +@ConfigurationProperties(prefix = "keycloak.ldapconfigprops")
Through the feature flag that we have at the controller, we can simply disable this feature. It need not be everywhere as this is the new code.

2023-01-06 05:58 UTC, merged